# Generated by Django 4.1.5 on 2023-03-02 06:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_onetimepassword_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='alley',
            field=models.CharField(max_length=50, verbose_name='alley'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.IntegerField(verbose_name='floor'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=5, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=50, verbose_name='street'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='code',
            field=models.PositiveSmallIntegerField(verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_operator',
            field=models.BooleanField(default=False, verbose_name='operator'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_product_manager',
            field=models.BooleanField(default=False, verbose_name='product manager'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_supervisor',
            field=models.BooleanField(default=False, verbose_name='supervisor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='phone number'),
        ),
    ]
