# Generated by Django 4.1.5 on 2023-03-02 07:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_address_options_alter_onetimepassword_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها'},
        ),
        migrations.AlterModelOptions(
            name='onetimepassword',
            options={'verbose_name': 'رمز یک بار مصرف', 'verbose_name_plural': 'رمز یک بار مصرف'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='address',
            name='alley',
            field=models.CharField(max_length=50, verbose_name='کوچه'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.IntegerField(verbose_name='طبقه'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=5, verbose_name='پلاک'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=50, verbose_name='خیابان'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='code',
            field=models.PositiveSmallIntegerField(verbose_name='کد تایید'),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='موبایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='ادمین'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_operator',
            field=models.BooleanField(default=False, verbose_name='اپراتور'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_product_manager',
            field=models.BooleanField(default=False, verbose_name='مدیر محصولات'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_supervisor',
            field=models.BooleanField(default=False, verbose_name='ناظر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='موبایل'),
        ),
    ]
