# Generated by Django 4.1.5 on 2023-03-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_address_options_alter_onetimepassword_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='ایجاد شده در'),
        ),
    ]
